import Head from "next/head";
import Image from "next/image";
import Navbar from "../navigation/Navbar";
import Footer from "../navigation/Footer";
import AirBnbCard from "../components/AirBnbCard";

import { Box, useColorModeValue } from "@chakra-ui/react";

import { ColorModeScript } from "@chakra-ui/react";
import { Link } from "@chakra-ui/react";
import { ExternalLinkIcon } from "@chakra-ui/icons";

import theme from "../theme";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      <Navbar />
      {/* <div className={styles.container}> */}
      <div className="flex flex-col items-center h-[400px] justify-center bg-gray-400">
        <div className="text-4xl text-blue-800">Siemanko. 🖐️</div>
        <div className="w-[700px] bg-gray-800 flex flex-col gap-3">
          <Link href="https://chakra-ui.com" isExternal>
            Chakra Design system <ExternalLinkIcon mx="2px" />
          </Link>
          <Link href="https://chakra-templates.dev/" isExternal>
            Chakra Templates https://chakra-templates.dev/ <ExternalLinkIcon mx="2px" />
          </Link>
        </div>
      </div>
      <section className="flex flex-col items-center h-[500px] justify-center">
        <Box
          bg={useColorModeValue("blackAlpha.100", "whiteAlpha.100")}
          w="100%"
          p={4}
          color="white"
          className="flex justify-center gap-5">
          <AirBnbCard />
          <AirBnbCard />
        </Box>
      </section>
      <Footer />
    </div>
  );
}
