import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-4xl text-blue-500">Siemanko. 🖐️</div>
      <div className="w-[500px] bg-pink-500">sprawdzam</div>
    </div>
  );
}
